### ISSUE TITLE
No npm dependencies in root

### ISSUE THREAD

**Issue by Osamah** [hello-ashleyintech/polygon-fauna-app#1]
In readme it says the following:

> 
> ## Install dependencies
> Once your `.env` is set up, install dependencies. You'll need to do the following:
> * In the root directory, run `npm install` (installs general product dependencies)
> 

However there is no package.json available in root so nothing gets installed... If you then run `truffle migrate --network matic --reset` to deploy the smart contracts you get errors saying there are packages not installed.

As far as I can see following packages are needed in root:
- @truffle/hdwallet-provider
- dotenv

**Comment by hello-ashleyintech** [comment]
PR from @Osamah resolving this - thanks so much! 🙌
